"""initial migration

Revision ID: dc5e258676ca
Revises: 
Create Date: 2026-05-17 18:56:57.481735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5e258676ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linhas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('empresa', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('terminal_inicial', sa.String(), nullable=True),
    sa.Column('terminal_final', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paradas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_parada', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prefixo', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('previsoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.Column('parada_id', sa.Integer(), nullable=True),
    sa.Column('tempo_chegada', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parada_id'], ['paradas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('previsoes')
    op.drop_table('veiculos')
    op.drop_table('paradas')
    op.drop_table('linhas')
    # ### end Alembic commands ###
